EBIvariation/variation-commons

src/main/java/embl/ebi/variation/commons/models/metadata/Organisation.java
src/test/java/embl/ebi/variation/commons/models/metadata/OrganisationTest.java
src/test/java/embl/ebi/variation/commons/models/metadata/database/OrganisationDatabaseTest.java
src/test/java/embl/ebi/variation/commons/models/metadata/database/OrganisationRepository.java

Organisation class annotated for database serialization using Spring Data JPA. The attribute "studies" is flagged as transient because it hasn't been annotated yet.

Organisation class serialisation

---

src/main/java/embl/ebi/variation/commons/models/metadata/Analysis.java
src/main/java/embl/ebi/variation/commons/models/metadata/Array.java
src/main/java/embl/ebi/variation/commons/models/metadata/FileGenerator.java
src/main/java/embl/ebi/variation/commons/models/metadata/Run.java
src/test/java/embl/ebi/variation/commons/models/metadata/AnalysisTest.java
src/test/java/embl/ebi/variation/commons/models/metadata/DatasetTest.java
src/test/java/embl/ebi/variation/commons/models/metadata/ExperimentTest.java
src/test/java/embl/ebi/variation/commons/models/metadata/FileGeneratorTest.java
src/test/java/embl/ebi/variation/commons/models/metadata/StudyTest.java

StudyTest: created separated test for adding analysys, runs and arrays

---

src/main/java/embl/ebi/variation/commons/models/metadata/Analysis.java
src/main/java/embl/ebi/variation/commons/models/metadata/FileGenerator.java
src/test/java/embl/ebi/variation/commons/models/metadata/database/AnalysisDatabaseTest.java
src/test/java/embl/ebi/variation/commons/models/metadata/database/AnalysisRepository.java

FileGenerator and Analysis classes annotated for database serialization using Spring Data JPA. The attributes "files", "dataset" and "study" in FileGenerator are flagged as transient.

FileGenerator and Analysis database serialisation

---

src/main/java/embl/ebi/variation/commons/models/metadata/Study.java
src/test/java/embl/ebi/variation/commons/models/metadata/StudyRelationTest.java
src/test/java/embl/ebi/variation/commons/models/metadata/StudyTest.java
src/test/java/embl/ebi/variation/commons/models/metadata/database/StudyDatabaseTest.java
src/test/java/embl/ebi/variation/commons/models/metadata/database/StudyRelationDatabaseTest.java

OneToMany relationship between parent and child studies. ManyToOne in reverse direction. Tests in "StudyRelationDatabaseTest" class to test these relationships.
Check added to parent and child studies setters, to check that a study isn't assigned itself as parent or child.

Serialisation of study relationships

---

src/main/java/embl/ebi/variation/commons/models/metadata/Organisation.java
src/main/java/embl/ebi/variation/commons/models/metadata/Study.java
src/test/java/embl/ebi/variation/commons/models/metadata/database/OrganisationDatabaseTest.java
src/test/java/embl/ebi/variation/commons/models/metadata/database/StudyDatabaseTest.java

Link between study and organisation, for centre and broker attributes in Study class, along with tests.
Removed "studies" attribute from Organisation.

Link between study and organisation

---

pom.xml
src/main/java/embl/ebi/variation/commons/models/data/FeatureCoordinates.java

This will be used in eva-ws and eva-pipeline.

add FeatureCoordinates bean

---

src/main/java/uk/ac/ebi/eva/commons/models/converters/data/MongoDBObjectToVariantConverter.java
src/main/java/uk/ac/ebi/eva/commons/models/converters/data/MongoDBObjectToVariantEntityConverter.java
src/main/java/uk/ac/ebi/eva/commons/models/metadata/VariantEntity.java
src/test/java/uk/ac/ebi/eva/commons/models/converters/data/MongoDBObjectToVariantConverterTest.java

- New VariantEntity class to allow specifying of collection
- Modified converter and test to accommodate this

EVA-450 Variant Entity class

---

src/main/java/uk/ac/ebi/eva/commons/models/converters/data/DbObjectToVariantGlobalStatsConverter.java

DbObjectToVariantGlobalStatsConverter for use with mongo repository for variant source entity

EVA-732 File stats in study view returns zero (DbObjectToVariantGlobalStatsConverter)

---

src/main/java/uk/ac/ebi/eva/commons/models/data/FeatureCoordinates.java
src/main/java/uk/ac/ebi/eva/commons/models/metadata/AnnotationMetadata.java
src/test/java/uk/ac/ebi/eva/commons/models/metadata/AnalysisTest.java
src/test/java/uk/ac/ebi/eva/commons/models/metadata/DatabaseTestConfiguration.java
src/test/resources/application.properties

Copied AnnotationMetadata from eva-pipeline

EVA-349 Copied AnnotationMetadata from eva-pipeline

---

pom.xml

EVA-349 Web service for VEP and Ensembl cache used (Updated pom version)

---

pom.xml
src/main/java/uk/ac/ebi/eva/commons/configuration/EvaRepositoriesConfiguration.java
src/main/java/uk/ac/ebi/eva/commons/core/models/Annotation.java
src/main/java/uk/ac/ebi/eva/commons/core/models/AnnotationMetadata.java
src/main/java/uk/ac/ebi/eva/commons/core/models/VariantSource.java
src/main/java/uk/ac/ebi/eva/commons/core/models/VariantStatistics.java
src/main/java/uk/ac/ebi/eva/commons/core/models/Xref.java
src/main/java/uk/ac/ebi/eva/commons/core/models/ws/VariantSourceEntryWithSampleNames.java
src/main/java/uk/ac/ebi/eva/commons/mongodb/entities/AnnotationMongo.java
src/main/java/uk/ac/ebi/eva/commons/mongodb/entities/FeatureCoordinatesMongo.java
src/main/java/uk/ac/ebi/eva/commons/mongodb/entities/VariantMongo.java
src/main/java/uk/ac/ebi/eva/commons/mongodb/entities/VariantSourceMongo.java
src/main/java/uk/ac/ebi/eva/commons/mongodb/entities/subdocuments/AnnotationIndexMongo.java
src/main/java/uk/ac/ebi/eva/commons/mongodb/entities/subdocuments/ConsequenceTypeMongo.java
src/main/java/uk/ac/ebi/eva/commons/mongodb/entities/subdocuments/VariantAtMongo.java
src/main/java/uk/ac/ebi/eva/commons/mongodb/entities/subdocuments/VariantSourceEntryMongo.java
src/main/java/uk/ac/ebi/eva/commons/mongodb/entities/subdocuments/VariantStatisticsMongo.java
src/main/java/uk/ac/ebi/eva/commons/mongodb/projections/SimplifiedVariant.java
src/main/java/uk/ac/ebi/eva/commons/mongodb/repositories/VariantRepositoryImpl.java
src/main/java/uk/ac/ebi/eva/commons/mongodb/services/VariantSourceService.java
src/main/java/uk/ac/ebi/eva/commons/mongodb/services/VariantWithSamplesAndAnnotationsService.java
src/test/java/uk/ac/ebi/eva/commons/configuration/MongoRepositoryTestConfiguration.java
src/test/java/uk/ac/ebi/eva/commons/mongodb/VariantStatsConversionTest.java
src/test/java/uk/ac/ebi/eva/commons/mongodb/services/AnnotationMetadataServiceTest.java
src/test/java/uk/ac/ebi/eva/commons/mongodb/services/VariantSourceServiceTest.java
src/test/java/uk/ac/ebi/eva/commons/mongodb/services/VariantStudySummaryServiceTest.java
src/test/java/uk/ac/ebi/eva/commons/mongodb/services/VariantWithSamplesAndAnnotationsServiceTest.java
src/test/java/uk/ac/ebi/eva/commons/test/configurations/MongoOperationsConfiguration.java
src/test/resources/eva.properties

- Equals and hashcode methods needed for equality checking
- null check of stats in VariantSource
- VariantSourceService needed for debugging

EVA-501 Changes needed for eva-ws after restructuring

---

src/main/java/uk/ac/ebi/eva/commons/core/models/VariantStatistics.java

Only calculate cohort stats if they actually should exist.

EVA-501 Move Java models and entities to variation-commons (fixes for eva-ws)

---

src/main/java/uk/ac/ebi/eva/commons/core/models/StudyType.java

DGVA-64 View list of studies- Added Somatic study type

---

pom.xml
src/main/java/uk/ac/ebi/eva/commons/core/models/ConsequenceType.java
src/main/java/uk/ac/ebi/eva/commons/core/models/ws/ScoreWithSource.java

- New ScoreWithSource for webservice response
- Set for proteinSubstitutionScores, for ws response

EVA-882 Web service protein substitution score structure different from production

---

pom.xml
src/main/java/uk/ac/ebi/eva/commons/core/models/VariantStatistics.java
src/main/java/uk/ac/ebi/eva/commons/mongodb/services/VariantWithSamplesAndAnnotationsService.java
src/test/java/uk/ac/ebi/eva/commons/mongodb/services/VariantWithSamplesAndAnnotationServiceTest.java

The code was recalculating the statistics when they were already available, and not calculating them when they were not! :fearful:

EVA-917 Do not recalculate statistics if already available

---

variation-commons-core/src/main/java/uk/ac/ebi/eva/commons/core/models/AbstractVariant.java
variation-commons-core/src/main/java/uk/ac/ebi/eva/commons/core/models/IVariant.java

Add an attribute mainId to Variant model

EVA-876 Map variants read from dbSNP database to EVA model

---

variation-commons-mongodb/src/main/java/uk/ac/ebi/eva/commons/mongodb/writers/VariantMongoWriter.java

VariantMongoWriter is generic enough to write all kinds of Variants. Using the interface makes easier to write other tools that use this writer.

EVA-913 part 2: VariantMongoWriter writes IVariant

---

.gitignore
variation-commons-core/src/main/java/uk/ac/ebi/eva/commons/core/models/factories/VariantVcfFactory.java
variation-commons-core/src/test/java/uk/ac/ebi/eva/commons/core/models/factories/VariantVcfFactoryTest.java

VariantVcfFactory.java, VariantVCFFactoryTest.java - Ignore variant IDs submitted through VCFs (see EVA-942)

EVA-942 - Ignore Variant IDs submitted through VCFs

---

variation-commons-mongodb/src/main/java/uk/ac/ebi/eva/commons/mongodb/repositories/VariantRepositoryCustom.java
variation-commons-mongodb/src/main/java/uk/ac/ebi/eva/commons/mongodb/repositories/VariantRepositoryImpl.java
variation-commons-mongodb/src/main/java/uk/ac/ebi/eva/commons/mongodb/services/VariantWithSamplesAndAnnotationsService.java
variation-commons-mongodb/src/test/java/uk/ac/ebi/eva/commons/mongodb/repositories/VariantRepositoryTest.java

Required changes to allow searching by a list of variant identifiers (issue #77 on eva-ws)

Required changes to allow searching by a list of variant identifiers

---

pom.xml

Needed for using beacon model in eva-ws

EVA-1524 Update swagger annotations dependency

---

variation-commons-mongodb/src/main/java/uk/ac/ebi/eva/commons/mongodb/repositories/VariantSourceRepository.java

Updated findAllForBeacon function to retrieve `fileId` as well

Updated findallForBeacon

---

variation-commons-mongodb/src/main/java/uk/ac/ebi/eva/commons/mongodb/repositories/FeatureRepository.java
variation-commons-mongodb/src/main/java/uk/ac/ebi/eva/commons/mongodb/services/FeatureService.java
variation-commons-mongodb/src/test/java/uk/ac/ebi/eva/commons/mongodb/services/FeatureServiceTest.java
variation-commons-mongodb/src/test/resources/test-data/features.json

The purpose of this PR is to add functions so that querying by a list of `geneIds` is possible

Add findAllBygeneIds functionality

---

variation-commons-mongodb/src/main/java/uk/ac/ebi/eva/commons/mongodb/services/VariantStudySummaryService.java
variation-commons-mongodb/src/test/java/uk/ac/ebi/eva/commons/mongodb/services/VariantStudySummaryServiceTest.java

The purpose of this PR is to add a function `findAll` function to `VariantStudySummaryService`
with pageNumber and pageSize as parameters

Added functions required for ArchiveWSServerV2 endpoint

---

variation-commons-batch/src/main/java/uk/ac/ebi/eva/commons/batch/io/CoordinatesVcfFactory.java
variation-commons-batch/src/main/java/uk/ac/ebi/eva/commons/batch/io/CoordinatesVcfLineMapper.java
variation-commons-batch/src/test/java/uk/ac/ebi/eva/commons/batch/io/CoordinatesVcfReaderTest.java
variation-commons-core/src/main/java/uk/ac/ebi/eva/commons/core/models/factories/CoordinatesVcfFactory.java
variation-commons-core/src/test/java/uk/ac/ebi/eva/commons/core/models/factories/CoordinatesVcfFactoryTest.java

Moved CoordinatesVcfLineMapper and CoordinatesVcfFactory from eva-accession.

EVA-1942 Polish the clustering pipeline (1/2)
